const MAPEAMENTO_PIPEFY = {
  
    'Digite o Nome Completo do Locatário': 'nomeLocatario',
    'Digite o RG do locatário': 'RGLocatario',
    'Digite o CPF do Locatário': 'CPFLocatario', 
    'Digite o whatsapp do Locatário': 'celular',
    'Digite o e-mail do Locatário': 'email',
    'Digite o Endereço Residencial da Locação': 'enderecoImovel',
    'Valor mensal do aluguel': 'valorAluguel',
    'Digite o Nome do Fiador Completo': 'nomeFiador1',
    'Digite o RG do Fiador': 'RGFiador1',
    'Digite o CPF do Fiador': 'CPFFiador1',
    'Digite o Endereço Residencial Completo do Fiador': 'enderecoFiador1',
    'Digite o Whatsapp do Fiador': 'celularFiador1',
    'Digite o e-mail do Fiador': 'emailFiador1',
    'Nº de Matrícula (COPASA)': 'matriculaCopasa',
    'Nº do Hidrômetro (COPASA)': 'hidrometro',
    'Nº de Instalação CEMIG': 'CemigInstalacao',
    'Nº do Medidor (CEMIG)': 'numeroMedidor',
    'IPTU' : 'IPTUimovel',
    'Nº Inscrição Cadastral IPTU' :'InscricaoIPTU',
    'Nome do Proprietário': 'nomeProprietario',
    'CPF do Proprietário': 'CPFProprietario',
    'RG do Proprietário': 'RGProprietario', 
    'Endereço do Proprietário': 'enderecoProprietario',
    'Email do Proprietário': 'emailProprietario',
    'Telefone do Proprietário': 'celProprietario',
    'Banco': 'banco',
    'Agência': 'agencia',
    'Conta Corrente': 'conta',
    'Chave PIX': 'pix',
    
};

module.exports = MAPEAMENTO_PIPEFY;