const MAPEAMENTO_PIPEFY = {
  
    'Digite o Nome Completo do Locatário': 'nomeLocatario',
    'Digite o RG do locatário': 'RGLocatario',
    'Digite o CPF do Locatário': 'CPFLocatario',
    'Selecione a Nacionalidade do Locatário':'nacionalidadeLocatario',
    'Escolha o Estado Civil do Locatário': 'estadoCivilLocatario',
    'Digite a Profissão do Locatário': 'profissaoLocatario',
    'Digite o whatsapp do Locatário': 'celular',
    'Digite o e-mail do Locatário': 'email',
    'Digite o Endereço Residencial da Locação': 'enderecoImovel',
    'Digite o Endereço Residencial da Locação': 'enderecoLocatario',  
    'Digite as características do imóvel': 'caracteristicasImovel',
    'Digite o Valor do Aluguel': 'valorAluguel',
    'Digite o Nome do Fiador Completo': 'nomeFiador1',
    'Selecione a Nacionalidade do Fiador': 'nacionalidadeFiador1',
    'Selecione o Estado Civil do Fiador' : 'estadoCivilFiador1',
    'Digite a Profissão do Fiador':'profissaoFiador',
    'Digite o RG do Fiador': 'RGFiador1',
    'Digite o CPF do Fiador': 'CPFFiador1',
    'Digite o Endereço Residencial Completo do Fiador': 'enderecoFiador1',
    'Digite o Whatsapp do Fiador': 'celularFiador1',
    'Digite o e-mail do Fiador': 'emailFiador1',
    'Digite o Valor do Aluguel:': 'valorLocacaoMensal',
    'Nº de Matrícula (COPASA)': 'matriculaCopasa',
    'Nº do Hidrômetro (COPASA)': 'hidrometroCopasa',
    'Nº de Instalação CEMIG': 'CemigInstalacao',
    'Nº do Medidor (CEMIG)': 'numeroMedidor',
    'IPTU' : 'IPTUImovel',
    'Nº Inscrição Cadastral IPTU' :'InscricaoIPTU',
    'Nome do Proprietário': 'nomeProprietario',
    'Estado Civil do proprietário': 'estadoCivilProprietario',
    'Profissão do Proprietário': 'profissaoProprietario',
    'CPF do Proprietário': 'CPFProprietario',
    'RG do Proprietário': 'RGProprietario', 
    'Endereço do Proprietário': 'enderecoProprietario',
    'Email do Proprietário': 'emailProprietario',
    'Telefone do Proprietário': 'celProprietario',
    'Banco': 'banco',
    'Agência': 'agencia',
    'Conta Corrente': 'conta',
    'Chave PIX': 'pix',
    'RG': 'RGLocatario',
};

module.exports = MAPEAMENTO_PIPEFY;